language: ruby
rvm: 2.0.0

branches:
  only:
    - develop

before_script:
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ $GH_TOKEN ] && rake setup'
script:
  - 'rake build'
after_script:
  - '[ "$TRAVIS_BRANCH" == "develop" ] && [ $GH_TOKEN ] && rake push'

env:
  global:
    - GIT_COMMITER_NAME="tamaxyo"
    - GIT_COMMITER_EMAIL="tamaxyo@gmail.com"
    - GIT_AUTHOR_NAME="tamaxyo"
    - GIT_AUTHOR_EMAIL="tamaxyo@gmail.com"
    - secure: "SSgRxeTu6l+laeucCTxyw9cKOnt4OoRNSUjnSBADJZFWnPoAEPk7peed6uVPzvUxsHP6CjDOSPPQ8S5TXfAV/PxQzMT9MlM967c89kjdPIKZs34TXA3brlHcDhd5qoSz7dV0nEmauldwm67/KpPylBoo+2JjfkdPheSTj+Fa7HQ="
